name: using expressions
on:
  workflow_dispatch:
    inputs:
        debug:
            default: false
            type: boolean
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[Debug] Print start-up data"
        if: inputs.debug
        run: |
          echo "Debug mode is ON"
          echo "workflow name: ${{github.workflow}}"
          echo "Run ID: ${{github.run_id}}"
          echo "Run nunber: ${{github.run_number}}"
          echo "Event name: ${{github.event_name}}"
          echo "Actor: ${{github.actor}}"
          echo "Respository: ${{github.repository}}"
          echo "Branch: ${{github.ref_name}}"
          echo "SHA: ${{github.sha}}"
      - name: "[Debug] Print when triggered from main"
        if: inputs.debug && github.ref_name == 'main'
        run: |
          echo "This workflow was triggered form the main branch"
      - name: Greeting
        run: |
          echo "Hello, ${{github.actor}} Welcome to using expressions workflow"