name: nightly_housekeeper
on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at midnight UTC
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Print current date and time
        run: date

      - name: Print cleanup message
        run: echo "Running nightly cleanup."

      - name: Finish housekeeping
        run: echo "Housekeeping complete."